# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 33f209cdc0c0d9c49661a2d98c7ad3f0a7393a42267f62f7b6c3dd937d88caca37b7434a3ad3ae5309b92cdb23317bde80459efdb62b6efc647a7a733e6df206

test:
  secret_key_base: e7aa842b16cd794fd71bcd16899a3732632b30b473b72dee0072e321dfee4e6336387acba43e6fcb671b9524e4ddb8e23b5e70f08a5247757e9e1bba4127f53c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
